repos:
    # general hooks to verify or beautify code
    - repo: http://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      - id: check-added-large-files
        args: [--maxkb=100000]
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        args: [
          --allow-missing-credentials,
          --credentials-file, docker-compose/.env,
        ]
      - id: detect-private-key
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [--autofix]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer

    # autoformat code with black formatter
    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
        - id: black
          args: [-l 120]

    # check code style
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
        - id: flake8
          additional_dependencies: [flake8-quotes]
          args: [--config, .flake8]

    # sort imports
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          files: ^(breastcancer|tests)
          args: ["--profile", "black", "--trailing-comma", "--multi-line", "3"]

    # autodelete unused imports
    - repo: https://github.com/hadialqattan/pycln
      rev: v2.1.3
      hooks:
        - id: pycln
          args: [ --all ]
